import express from 'express';
import session from 'express-session';
import axios from 'axios';
import dotenv from 'dotenv';
import Database from 'better-sqlite3';
import crypto from 'node:crypto';
dotenv.config();
const app=express(), PORT=Number(process.env.PORT||4000), db=new Database('mars.sqlite');
db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,kakao_id TEXT UNIQUE,nickname TEXT NOT NULL,cash INTEGER NOT NULL DEFAULT 100000,bank INTEGER NOT NULL DEFAULT 0,last_attendance TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS stocks(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT UNIQUE,name TEXT,price INTEGER,change REAL DEFAULT 0); CREATE TABLE IF NOT EXISTS holdings(user_id INTEGER,stock_id INTEGER,qty INTEGER DEFAULT 0,PRIMARY KEY(user_id,stock_id)); CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE,price INTEGER,stock INTEGER); CREATE TABLE IF NOT EXISTS product_holdings(user_id INTEGER,product_id INTEGER,qty INTEGER DEFAULT 0,PRIMARY KEY(user_id,product_id)); CREATE TABLE IF NOT EXISTS properties(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,price INTEGER,income INTEGER); CREATE TABLE IF NOT EXISTS property_holdings(user_id INTEGER,property_id INTEGER,bought_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS factories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,price INTEGER,output INTEGER); CREATE TABLE IF NOT EXISTS factory_holdings(user_id INTEGER,factory_id INTEGER,level INTEGER DEFAULT 1); CREATE TABLE IF NOT EXISTS bonds(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,principal INTEGER,rate REAL,days INTEGER); CREATE TABLE IF NOT EXISTS bond_holdings(user_id INTEGER,bond_id INTEGER,principal INTEGER,started_at TEXT); CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,reporter_id INTEGER,target TEXT,reason TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP); CREATE TABLE IF NOT EXISTS world(key TEXT PRIMARY KEY,value TEXT);`);
const get=(s,...a)=>db.prepare(s).get(...a), all=(s,...a)=>db.prepare(s).all(...a), run=(s,...a)=>db.prepare(s).run(...a), won=n=>Number(n).toLocaleString('ko-KR')+'원';
function seed(){
if(!get('SELECT 1 FROM stocks LIMIT 1')) [['MARS','마르스',12500,3.2],['TECH','테크',15300,5.7],['BANK','은행',6820,0],['ENERGY','에너지',9100,-1.8],['FOOD','식품',5300,1.1]].forEach(x=>run('INSERT INTO stocks(code,name,price,change) VALUES(?,?,?,?)',...x));
if(!get('SELECT 1 FROM products LIMIT 1')) [['철강',2500,1000],['식량',1200,5000],['전자부품',7800,500],['석유',6200,800],['목재',1800,1500]].forEach(x=>run('INSERT INTO products(name,price,stock) VALUES(?,?,?)',...x));
if(!get('SELECT 1 FROM properties LIMIT 1')) [['소형 아파트',180000,3500],['상가',450000,10000],['공장부지',800000,18000],['랜드마크',2000000,50000]].forEach(x=>run('INSERT INTO properties(name,price,income) VALUES(?,?,?)',...x));
if(!get('SELECT 1 FROM factories LIMIT 1')) [['소형 공장',250000,5000],['중형 공장',700000,18000],['대형 공장',1800000,50000]].forEach(x=>run('INSERT INTO factories(name,price,output) VALUES(?,?,?)',...x));
if(!get('SELECT 1 FROM bonds LIMIT 1')) [['국채 A',10000,2.5,7],['국채 B',50000,4,30],['국채 C',100000,6.5,90]].forEach(x=>run('INSERT INTO bonds(name,principal,rate,days) VALUES(?,?,?,?)',...x));
run("INSERT OR IGNORE INTO world(key,value) VALUES('population','1000000')"); run("INSERT OR IGNORE INTO world(key,value) VALUES('gdp','125000000000')"); } seed();
function user(id,n='사용자'){let u=get('SELECT * FROM users WHERE kakao_id=?',String(id)); if(!u){run('INSERT INTO users(kakao_id,nickname) VALUES(?,?)',String(id),n);u=get('SELECT * FROM users WHERE kakao_id=?',String(id));} return u;}
function help(t){const h={계좌:'>계좌\n>출석\n>송금 @닉네임 금액',주식:'>시장\n>주식매수 MARS 10\n>주식매도 MARS 5\n>보유주식',부동산:'>부동산목록\n>부동산구매 번호\n>내부동산',공장:'>공장목록\n>공장구매 번호\n>내공장\n>생산 번호',상품:'>상품시장\n>상품구매 상품명 수량',채권:'>채권목록\n>채권구매 번호 금액',보장:'>보장',예적금:'>예금 금액\n>출금 금액',국가:'>국가\n>인구',또박:'>또박',신고:'>신고 @닉네임 사유',세계:'>세계',시스템:'>시스템'}; return h[t]||'[ 💰 마르스 경제봇 ]\n\n├ >도움말 계좌\n├ >도움말 주식\n├ >도움말 부동산\n├ >도움말 공장\n├ >도움말 상품\n├ >도움말 채권\n├ >도움말 보장\n├ >도움말 예적금\n├ >도움말 국가\n├ >도움말 또박\n├ >도움말 신고\n├ >도움말 세계\n└ >도움말 시스템\n\n[ 🚀 빠른 시작 ]\n├ >계좌\n├ >출석\n├ >송금 @닉네임 금액\n├ >시장\n├ >상품시장\n├ >부동산목록\n├ >공장목록\n└ >인구';}
function command(u,raw){const p=String(raw).trim().split(/\s+/),c=p[0],a=p.slice(1);
if(c==='>도움말')return help(a[0]); if(c==='>계좌')return '💳 [ 계좌 정보 ]\n닉네임 : '+u.nickname+'\n현금 : '+won(u.cash)+'\n예금 : '+won(u.bank);
if(c==='>출석'){const d=new Date().toISOString().slice(0,10);if(u.last_attendance===d)return '📅 오늘은 이미 출석했습니다.';const b=1000+Math.floor(Math.random()*4001);run('UPDATE users SET cash=cash+?,last_attendance=? WHERE id=?',b,d,u.id);return '🎁 출석 완료!\n보너스 '+won(b)+' 지급';}
if(c==='>송금'){if(a.length<2)return '사용법: >송금 @닉네임 금액';const to=get('SELECT * FROM users WHERE nickname=?',a[0].replace(/^@/,'')),n=Number(a[1]);if(!to||!Number.isInteger(n)||n<=0)return '받는 사람 또는 금액을 확인하세요.';if(to.id===u.id)return '자기 자신에게 송금할 수 없습니다.';if(u.cash<n)return '현금 잔액이 부족합니다.';const tx=db.transaction(()=>{run('UPDATE users SET cash=cash-? WHERE id=?',n,u.id);run('UPDATE users SET cash=cash+? WHERE id=?',n,to.id)});tx();return '💸 송금 완료\n'+u.nickname+' → '+to.nickname+'\n금액 : '+won(n);}
if(c==='>시장')return '📈 [ 주식시장 ]\n'+all('SELECT code,name,price,change FROM stocks').map(x=>x.code+' '+x.name+' '+won(x.price)+' '+(x.change>=0?'▲':'▼')+' '+Math.abs(x.change)+'%').join('\n');
if(c==='>주식매수'||c==='>주식매도'){const s=get('SELECT * FROM stocks WHERE code=?',String(a[0]||'').toUpperCase()),n=Number(a[1]);if(!s||!Number.isInteger(n)||n<=0)return '종목 또는 수량을 확인하세요.';const cost=s.price*n,h=get('SELECT * FROM holdings WHERE user_id=? AND stock_id=?',u.id,s.id);if(c==='>주식매수'){if(u.cash<cost)return '현금이 부족합니다.';run('UPDATE users SET cash=cash-? WHERE id=?',cost,u.id);h?run('UPDATE holdings SET qty=qty+? WHERE user_id=? AND stock_id=?',n,u.id,s.id):run('INSERT INTO holdings VALUES(?,?,?)',u.id,s.id,n);return '📈 '+s.name+' '+n+'주 매수 완료\n금액 '+won(cost);}if(!h||h.qty<n)return '보유 주식이 부족합니다.';run('UPDATE holdings SET qty=qty-? WHERE user_id=? AND stock_id=?',n,u.id,s.id);run('UPDATE users SET cash=cash+? WHERE id=?',cost,u.id);return '📉 '+s.name+' '+n+'주 매도 완료\n정산 '+won(cost);}
if(c==='>보유주식'){const r=all('SELECT s.code,s.name,h.qty,s.price FROM holdings h JOIN stocks s ON s.id=h.stock_id WHERE h.user_id=? AND h.qty>0',u.id);return '📊 [ 보유 주식 ]\n'+(r.length?r.map(x=>x.code+' '+x.name+' '+x.qty+'주 / '+won(x.qty*x.price)).join('\n'):'보유 주식 없음');}
if(c==='>상품시장')return '🛒 [ 상품시장 ]\n'+all('SELECT id,name,price,stock FROM products').map(x=>x.id+'. '+x.name+' '+won(x.price)+' / 재고 '+x.stock).join('\n');
if(c==='>상품구매'){const p=get('SELECT * FROM products WHERE name=?',a[0]),n=Number(a[1]);if(!p||!Number.isInteger(n)||n<=0)return '상품 또는 수량을 확인하세요.';const cost=p.price*n;if(p.stock<n)return '상품 재고가 부족합니다.';if(u.cash<cost)return '현금이 부족합니다.';run('UPDATE users SET cash=cash-? WHERE id=?',cost,u.id);run('UPDATE products SET stock=stock-? WHERE id=?',n,p.id);run('INSERT INTO product_holdings VALUES(?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET qty=qty+excluded.qty',u.id,p.id,n);return '🛒 '+p.name+' '+n+'개 구매 완료\n'+won(cost);}
if(c==='>부동산목록')return '🏠 [ 부동산 목록 ]\n'+all('SELECT id,name,price,income FROM properties').map(x=>x.id+'. '+x.name+' / '+won(x.price)+' / 일수익 '+won(x.income)).join('\n');
if(c==='>부동산구매'){const p=get('SELECT * FROM properties WHERE id=?',Number(a[0]));if(!p)return '번호를 확인하세요.';if(u.cash<p.price)return '현금이 부족합니다.';run('UPDATE users SET cash=cash-? WHERE id=?',p.price,u.id);run('INSERT INTO property_holdings(user_id,property_id) VALUES(?,?)',u.id,p.id);return '🏠 '+p.name+' 구매 완료\n가격 '+won(p.price);}
if(c==='>내부동산'){const r=all('SELECT p.name,p.income FROM property_holdings h JOIN properties p ON p.id=h.property_id WHERE h.user_id=?',u.id);return '🏠 [ 보유 부동산 ]\n'+(r.length?r.map(x=>x.name+' / 일수익 '+won(x.income)).join('\n'):'없음');}
if(c==='>공장목록')return '🏭 [ 공장 목록 ]\n'+all('SELECT id,name,price,output FROM factories').map(x=>x.id+'. '+x.name+' / '+won(x.price)+' / 생산 '+won(x.output)).join('\n');
if(c==='>공장구매'){const f=get('SELECT * FROM factories WHERE id=?',Number(a[0]));if(!f)return '번호를 확인하세요.';if(u.cash<f.price)return '현금이 부족합니다.';run('UPDATE users SET cash=cash-? WHERE id=?',f.price,u.id);run('INSERT INTO factory_holdings(user_id,factory_id) VALUES(?,?)',u.id,f.id);return '🏭 '+f.name+' 구매 완료';}
if(c==='>내공장'){const r=all('SELECT f.name,h.level,f.output*h.level output FROM factory_holdings h JOIN factories f ON f.id=h.factory_id WHERE h.user_id=?',u.id);return '🏭 [ 보유 공장 ]\n'+(r.length?r.map(x=>x.name+' Lv.'+x.level+' / 생산 '+won(x.output)).join('\n'):'없음');}
if(c==='>생산'){const f=get('SELECT f.* FROM factory_holdings h JOIN factories f ON f.id=h.factory_id WHERE h.user_id=? AND f.id=?',u.id,Number(a[0]));if(!f)return '보유 공장을 확인하세요.';run('UPDATE users SET cash=cash+? WHERE id=?',f.output,u.id);return '🏭 생산 완료\n생산수익 '+won(f.output)+' 지급';}
if(c==='>채권목록')return '📜 [ 채권 ]\n'+all('SELECT id,name,principal,rate,days FROM bonds').map(x=>x.id+'. '+x.name+' / 최소 '+won(x.principal)+' / '+x.rate+'% / '+x.days+'일').join('\n');
if(c==='>채권구매'){const b=get('SELECT * FROM bonds WHERE id=?',Number(a[0])),n=Number(a[1]);if(!b||!Number.isInteger(n)||n<b.principal||u.cash<n)return '채권 번호/금액 또는 잔액을 확인하세요.';run('UPDATE users SET cash=cash-? WHERE id=?',n,u.id);run('INSERT INTO bond_holdings VALUES(?,?,?,?)',u.id,b.id,n,new Date().toISOString());return '📜 '+b.name+' '+won(n)+' 가입 완료';}
if(c==='>예금'){const n=Number(a[0]);if(!Number.isInteger(n)||n<=0||u.cash<n)return '예금 금액을 확인하세요.';run('UPDATE users SET cash=cash-?,bank=bank+? WHERE id=?',n,n,u.id);return '🏦 '+won(n)+' 예금 완료';}
if(c==='>출금'){const n=Number(a[0]);if(!Number.isInteger(n)||n<=0||u.bank<n)return '예금 잔액을 확인하세요.';run('UPDATE users SET cash=cash+?,bank=bank-? WHERE id=?',n,n,u.id);return '🏦 '+won(n)+' 출금 완료';}
if(c==='>인구')return '👥 현재 인구 : '+Number(get("SELECT value FROM world WHERE key='population'").value).toLocaleString()+'명';
if(c==='>국가')return '🌐 [ 마르스 국가 ]\n국가명 : 마르스 연합\n경제규모 : '+Number(get("SELECT value FROM world WHERE key='gdp'").value).toLocaleString()+'\n인구 : '+Number(get("SELECT value FROM world WHERE key='population'").value).toLocaleString()+'명';
if(c==='>세계')return '🌍 [ 세계 현황 ]\n세계 경제 규모 : '+Number(get("SELECT value FROM world WHERE key='gdp'").value).toLocaleString()+'\n인구 : '+Number(get("SELECT value FROM world WHERE key='population'").value).toLocaleString();
if(c==='>또박'){const b=500+Math.floor(Math.random()*9501);run('UPDATE users SET cash=cash+? WHERE id=?',b,u.id);return '🎲 오늘의 또박\n보너스 '+won(b)+' 지급!';}
if(c==='>신고'){if(a.length<2)return '사용법: >신고 @닉네임 사유';run('INSERT INTO reports(reporter_id,target,reason) VALUES(?,?,?)',u.id,a[0],a.slice(1).join(' '));return '🚨 신고가 접수되었습니다.';}
if(c==='>보장')return '🛡️ 보장 시스템\n가상경제용 보장 메뉴입니다.'; if(c==='>시스템')return '⚙️ 마르스 경제봇 v1.0\nDB: SQLite\n경제엔진: 활성\n명령어 엔진: 활성'; return '❓ 알 수 없는 명령어입니다.\n>도움말 을 입력해보세요.';}
app.use(express.json()); app.use(express.urlencoded({extended:true})); app.use(session({secret:process.env.SESSION_SECRET||'mars-secret',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax'}}));
app.get('/',(req,res)=>res.type('html').send('<!doctype html><meta charset="utf-8"><title>💰 마르스 경제봇</title><style>body{font-family:Arial;max-width:850px;margin:40px auto;padding:20px}button,input{padding:10px;margin:4px}pre{background:#111;color:#eee;padding:16px;white-space:pre-wrap}</style><h1>💰 마르스 경제봇</h1><p>경제 엔진 테스트 콘솔</p>'+(req.session.kakaoId?'<p>로그인: '+req.session.nickname+'</p><form method="post" action="/test"><input name="command" style="width:70%" placeholder=">계좌"><button>실행</button></form><pre>'+String(req.session.last||'명령어를 입력하세요.').replaceAll('<','&lt;')+'</pre><a href="/logout">로그아웃</a>':'<a href="/oauth/kakao"><button>카카오 로그인</button></a>'));
app.get('/oauth/kakao',(req,res)=>{const state=crypto.randomBytes(16).toString('hex');req.session.oauthState=state;const p=new URLSearchParams({response_type:'code',client_id:process.env.KAKAO_REST_API_KEY,redirect_uri:process.env.KAKAO_REDIRECT_URI,state});res.redirect('https://kauth.kakao.com/oauth/authorize?'+p)});
app.get('/oauth/kakao/callback',async(req,res)=>{try{if(req.query.state!==req.session.oauthState)return res.status(400).send('state 오류');const b=new URLSearchParams({grant_type:'authorization_code',client_id:process.env.KAKAO_REST_API_KEY,redirect_uri:process.env.KAKAO_REDIRECT_URI,code:req.query.code});if(process.env.KAKAO_CLIENT_SECRET)b.set('client_secret',process.env.KAKAO_CLIENT_SECRET);const t=await axios.post('https://kauth.kakao.com/oauth/token',b.toString(),{headers:{'Content-Type':'application/x-www-form-urlencoded'}});const me=await axios.get('https://kapi.kakao.com/v2/user/me',{headers:{Authorization:'Bearer '+t.data.access_token}});const u=user(me.data.id,me.data.properties?.nickname||'사용자');req.session.kakaoId=String(me.data.id);req.session.nickname=u.nickname;req.session.accessToken=t.data.access_token;res.redirect('/')}catch(e){console.error(e.response?.data||e);res.status(500).send('카카오 로그인 실패')}});
app.post('/test',(req,res)=>{if(!req.session.kakaoId)return res.redirect('/oauth/kakao');req.session.last=command(user(req.session.kakaoId,req.session.nickname),req.body.command||'');res.redirect('/')});
app.post('/api/command',(req,res)=>{if(!req.session.kakaoId)return res.status(401).json({error:'login_required'});res.json({reply:command(user(req.session.kakaoId,req.session.nickname),req.body.command||'')})});
app.post('/api/bot/message',(req,res)=>{if(process.env.BOT_WEBHOOK_SECRET&&req.get('x-bot-secret')!==process.env.BOT_WEBHOOK_SECRET)return res.status(401).json({error:'unauthorized'});const x=req.body;if(!x.kakao_id||!x.message)return res.status(400).json({error:'kakao_id,nickname,message required'});res.json({reply:command(user(x.kakao_id,x.nickname||'사용자'),x.message)})});
app.get('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/'))); app.listen(PORT,()=>console.log('💰 Mars Economy Bot: http://localhost:'+PORT));